### ISSUE TITLE
Couldn't get Spotify playlist: Resource not found

### ISSUE THREAD

**Issue by kalpik** [Zibbp/tidal-utils#9]
Hi!

I had set this up yesterday, and it was working great! But now today, I am getting this error:

`2024-11-28T06:32:36.100532160Z time="2024-11-28T06:32:36Z" level=info msg="Tidal access token is valid."

2024-11-28T06:32:36.105617955Z time="2024-11-28T06:32:36Z" level=info msg="Manual mode enabled."

2024-11-28T06:32:36.885549239Z time="2024-11-28T06:32:36Z" level=error msg="Couldn't get playlist: Resource not found"

2024-11-28T06:32:36.885591088Z time="2024-11-28T06:32:36Z" level=error msg="Couldn't get Spotify playlist: Resource not found"

2024-11-28T06:32:36.887747810Z panic: runtime error: invalid memory address or nil pointer dereference

2024-11-28T06:32:36.887797539Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71d3d5]

2024-11-28T06:32:36.887804820Z 

2024-11-28T06:32:36.887810348Z goroutine 1 [running]:

2024-11-28T06:32:36.887815569Z github.com/zibbp/tidal-utils/internal/spotify.(*Service).GetPlaylists(0xc0000c2000?, {{0xc0005956e0?, 0xc0000e4e68?, 0x1?}})

2024-11-28T06:32:36.887821942Z 	/app/internal/spotify/spotify.go:18 +0x115

2024-11-28T06:32:36.887827400Z main.spotifyToTidal(0xc000083d40?, 0xc00009c640)

2024-11-28T06:32:36.887832832Z 	/app/cmd/main.go:78 +0x249

2024-11-28T06:32:36.887838335Z main.main()

2024-11-28T06:32:36.887844604Z 	/app/cmd/main.go:42 +0x86`

I've double checked the playlist IDs in playlists.json, and they are correct. Not sure what happened.

**Comment by Zibbp** [comment]
Hi,
Can you try my other spotify to Tidal converter? This one is newer and will replace this one eventually https://github.com/Zibbp/spotify-playlist-sync

**Comment by kalpik** [comment]
Hmm, I have a feeling something else is going on.

See this playlist: https://open.spotify.com/playlist/37i9dQZF1DWWMOmoXKqHTD

If I try get the playlist via API, I get 404. You can try here: https://developer.spotify.com/documentation/web-api/reference/get-playlist

**Comment by kalpik** [comment]
> Hi, Can you try my other spotify to Tidal converter? This one is newer and will replace this one eventually https://github.com/Zibbp/spotify-playlist-sync

The new one looks nice. I will wait till I have the ability to choose which playlists I want to sync :)

**Comment by kalpik** [comment]
Seems like any playlist ID that begins with 37 (by Spotify), is somehow not searchable via the API anymore.

**Comment by kalpik** [comment]
Ah, this is a breaking change indeed: https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api
